### ISSUE TITLE
Gem version 0.0.2 is missing on Rubygems

### ISSUE THREAD

**Issue by morgoth** [Fred-grais/transifex-interface-ruby#14]
There was a tag pushed to github with 0.0.2 version, but the gem is still missing on Rubygems https://rubygems.org/gems/transifex-interface-ruby
@Fred-grais Can you please release it?

**Comment by klaseskilson** [comment]
Would really appreciate this too! Any updates, @Fred-grais?

**Comment by Fred-grais** [comment]
Hello been busy lately,

Just pushed the new version on RubyGem,

Merry Christmas
