### ISSUE TITLE
Resource source updates

### ISSUE THREAD

**Issue by Habu-Kagumba** [Fred-grais/transifex-interface-ruby#8]
When updating the resource content, maybe there should be a similar `:trad_from_file` option. This enables allowing using other i18n_types (kinda like how it's done in the Resource create method).
Other formats are not officially supported by this gem like XLIFF but still usable. I've been using XLIFF without any problems.

**Comment by Fred-grais** [comment]
Hello,

thanks for your feedbacks,

I merged your pull request containing the aforementioned changes into the master branch
